MauroDataMapper/mdm-ui

src/app/folders-tree/folders-tree.component.ts, src/app/import-models/import-models.component.ts, src/app/model-selector-tree/model-selector-tree.component.ts, src/app/services/model-tree.service.ts, src/app/shared/models/models.component.html, src/app/shared/models/models.component.ts
* Track when model tree view has selected a node
* Have import-models component pre-select chosen folder matching current model tree if a folder is selected
Fixes #92
=> #92 Update tree controls to pre-select folder for import

custom-webpack.config.js, src/app/services/shared.model.ts, src/environments/env.d.ts, src/environments/environment.prod.ts, src/environments/environment.ts
Currently development mode has this always on.
Production builds have this disabled by default, unless the environment variable MDM_UI_FEATURE_VERSIONED_FOLDERS is used in docker compose
=> MC-9516 Add feature toggle for versioned folders

package-lock.json, src/app/access/group-access-new.component.ts, src/app/access/share-with/share-with.component.ts, src/app/app-routing.module.ts, src/app/model/access.ts, src/app/model/editable-forms.ts, src/app/model/ui.model.ts, src/app/modules/catalogue/catalogue.module.ts, src/app/modules/resources/mdm-resources.service.ts, src/app/profile-base/profile-base.component.ts, src/app/services/editing.service.ts, src/app/services/handlers/security-handler.model.ts, src/app/services/handlers/state-handler.service.ts, src/app/utility/editable-form-buttons/editable-form-buttons.component.html, src/app/utility/editable-form-buttons/editable-form-buttons.component.ts, src/app/utility/markdown/markdown-text-area/markdown-text-area.component.html, src/app/utility/markdown/markdown-text-area/markdown-text-area.component.ts, src/app/versioned-folder/versioned-folder-detail/versioned-folder-detail.component.html, src/app/versioned-folder/versioned-folder-detail/versioned-folder-detail.component.scss, src/app/versioned-folder/versioned-folder-detail/versioned-folder-detail.component.ts, src/app/versioned-folder/versioned-folder/versioned-folder.component.html, src/app/versioned-folder/versioned-folder/versioned-folder.component.scss, src/app/versioned-folder/versioned-folder/versioned-folder.component.ts
Create the parent/child detail view components to render the details for Versioned Folders. Displays:
* Standard details - a mixture of folder (container) properties and data model (versionable) properties
* Description tab
* Annotations tab
* History tab
* Rules tab
* User access/permissions
Known issues:
* Any versioned folders created are not yet visible in the tree, but can be accessed by their route URL
* The property metadata view of versioned folders do not work because profiles are not supported in the backend yet
The form editing capabilities of the parent/detail components has been changed to try and create state tracking objects for the forms. Some of the form details have been modified to use Angular reactive forms and `FormGroups` instead for tidier input changes and …
=> Feature/mc 9517 Detail views for Versioned Folders

src/app/utility/multiple-terms-selector/multiple-terms-selector.component.ts
Required `labelOnly` parameter to not be null. Fixes #156 
@jamesrwelch Please also review to ensure this is what you requested, otherwise please leave feedback for further changes.
=> #156 Fix term search in selector component

src/app/folders-tree/folders-tree.component.html, src/style/layout/_tree.scss
Adjust spacing to ensure nothing grows/shrinks depending on whether the item is selected or the contents of the item.
Fixes #180
=> #180 Fix styles for model tree items

custom-webpack.config.js, package-lock.json, package.json, src/app/app-routing.module.ts, src/app/app.module.ts, src/app/dataModel/data-model-detail.component.ts, src/app/merge-diff/merge-diff-adapter/merge-diff-adapter.service.spec.ts, src/app/merge-diff/merge-diff-adapter/merge-diff-adapter.service.ts, src/app/merge-diff/merge-diff-container/merge-diff-container.component.html, src/app/merge-diff/merge-diff-container/merge-diff-container.component.scss, src/app/merge-diff/merge-diff-container/merge-diff-container.component.spec.ts, src/app/merge-diff/merge-diff-container/merge-diff-container.component.ts, src/app/merge-diff/merge-diff.module.ts, src/app/referenceData/reference-data-details/reference-data-details.component.ts, src/app/services/handlers/state-handler.service.ts, src/app/services/shared.model.ts, src/app/testing/testing.helpers.ts, src/app/testing/testing.module.ts, src/environments/env.d.ts, src/environments/environment.prod.ts, src/environments/environment.ts
* Added the feature flag to use new Merge UI. Enabled for development, can be turned on in production via `MDM_UI_USE_MERGE_V2` environment variable in docker compose
* Created separate Angular module called `MergeDiffModule` to declare/provide all the components/services specifically for this merge/diff feature
* Updated action points in Data Model views to navigate to the new Merge UI using a new route if enabled. New UI is simply a skeleton to fill in at this point.
* Included updated `TestingModule` and testing helper functions for easier `*.spec.ts` file setup with correct modules already imported.
=> Feature/mc 9546 Feature flag and module for new Merge Diff UI

angular.json, src/app/folders-tree/folders-tree.component.ts, src/app/import-models/import-models.component.html, src/app/import-models/import-models.component.ts, src/app/model-selector-tree/model-selector-tree.component.ts, webpack.config.js
* Ensure that Versioned Folders are visible in the importer folder tree selection
* Only show folders that contain the `createModel` permission now - this ensures that finalised Versioned Folders can never be import targets
* Updated the layout styles of the importer page
**Note**: there is a known issue with importing models into Versioned Folders at the moment, the issue is on the backend: MauroDataMapper/mdm-core#89
=> Feature/mc 9551 Importer updates to support Versioned Folders

package-lock.json, src/app/code-set/code-set-details/code-set-details.component.html, src/app/code-set/code-set-details/code-set-details.component.ts, src/app/dataModel/data-model-detail.component.html, src/app/dataModel/data-model-detail.component.ts, src/app/modules/catalogue/catalogue.module.ts, src/app/modules/resources/mdm-resources.models.ts, src/app/modules/shared/shared.module.ts, src/app/referenceData/reference-data-details/reference-data-details.component.html, src/app/referenceData/reference-data-details/reference-data-details.component.ts, src/app/services/element-types.service.ts, src/app/services/handlers/security-handler.service.ts, src/app/shared/branch-selector/branch-selector.component.html, src/app/shared/branch-selector/branch-selector.component.scss, src/app/shared/branch-selector/branch-selector.component.spec.ts, src/app/shared/branch-selector/branch-selector.component.ts, src/app/shared/new-version/new-version.component.html, src/app/shared/new-version/new-version.component.scss, src/app/shared/new-version/new-version.component.ts, src/app/terminology/terminology-details/terminology-details.component.html, src/app/terminology/terminology-details/terminology-details.component.ts, src/app/testing/testing.helpers.ts, src/app/testing/testing.module.ts, src/app/versioned-folder/versioned-folder-detail/versioned-folder-detail.component.html, src/app/versioned-folder/versioned-folder-detail/versioned-folder-detail.component.ts
* Add actions to navigate to `NewVersionComponent` from a Versioned Folder
* Tidy up the UI for the `NewVersionComponent`, especially text to make sure instructions make sense for both models and containers
* Created shared `BranchSelectorComponent` to use correct endpoint for getting version/branch list from a model/folder and update all detail views to use this now
**Note**: there is a known issue in the backend which prevents a new version/branch/fork being created for a Versioned Folder that has child content, see MauroDataMapper/mdm-core#88. Oddly, these actions do work on empty Versioned Folders though.
=> Feature/mc 9549 Enable Branch/Version/Fork for Versioned Folders

package-lock.json, src/app/subscribed-catalogues/federated-data-model-detail/federated-data-model-detail.component.ts
Send model type in request too to allow backend to know what type of model is being imported
Fixes #199 
**Note:** I have been unable to test this at the moment because of the date parsing bug from MauroDataMapper/mdm-core#90
=> #199 Fix subscribing to models in subscribed catalogues

src/app/admin/openid-connect-provider/openid-connect-provider.component.html, src/app/admin/openid-connect-provider/openid-connect-provider.component.ts, src/app/services/handlers/security-handler.service.ts
Show the `redirect_uri` to admins, required for OpenID Connect to work between identity providers.
=> MC-9573 Add info to OpenID Connect provider pages

src/app/shared/code-set-terms-table/code-set-terms-table.component.html, src/app/shared/code-set-terms-table/code-set-terms-table.component.ts, src/app/utility/multiple-terms-selector/multiple-terms-selector.component.html, src/app/utility/multiple-terms-selector/multiple-terms-selector.component.scss, src/app/utility/multiple-terms-selector/multiple-terms-selector.component.ts
Resolves #160 
Update `mdm-multiple-terms-selector` component to include an "Add all Terms" option:
If ticked, then every term in the selected terminology will be added to the parent code set. Untick to revert back to the manual search/filter selection list to pick terms.
=> Feature/gh 160 Include "Add all Terms" option to multi-term selector

src/app/modals/login-modal/login-modal.component.html, src/app/modals/login-modal/login-modal.component.scss
Resolves #251 
* Email/password form is now on left and OpenID Connect buttons are on right (if available)
* Mobile view will respond to stacking controls in a column
Desktop view:
Mobile view:
=> #251 Change layout of login dialog

src/app/merge-diff/conflict-editor/conflict-editor-modal/conflict-editor-modal.component.html, src/app/merge-diff/conflict-editor/conflict-editor-modal/conflict-editor-modal.component.ts, src/app/merge-diff/conflict-editor/string-conflict-editor/string-conflict-editor.component.html, src/app/merge-diff/conflict-editor/string-conflict-editor/string-conflict-editor.component.scss, src/app/merge-diff/conflict-editor/string-conflict-editor/string-conflict-editor.component.ts, src/app/merge-diff/merge-diff-container/merge-diff-container.component.ts
Resolves #250 
1. Removes user warning if conflicts are still found in resolved text. Must now remove every conflict before accepting.
2. Add "Take all" buttons to source/target views to for copying every change into resolved for fixing conflicts.
3. Fixed bug in cancelling all commits where branch name was still present.
=> Feature/gh 250 Feedback changes to new merge conflict editor

src/app/services/element-types.service.ts, src/app/shared/element-data-type/element-data-type.component.html, src/app/shared/element-data-type/element-data-type.component.ts, src/app/utility/new-data-type-inline/new-data-type-inline.component.html, src/app/utility/new-data-type-inline/new-data-type-inline.component.ts, src/app/wizards/dataElement/data-element-main/data-element-main.component.ts, src/app/wizards/dataType/data-type-main/data-type-main.component.ts, src/app/wizards/dataType/data-type-step2/data-type-step2.component.ts
Fixes #241
Fixes #157 
* Fixed issue when creating a new data type at the same time as a data element. If choosing a `ModelDataType`, the incorrect payload was sent to the `POST` endpoint.
* Updated the `mdm-element-data-type` component to correctly display `ModelDataType` details and their linked models as links
=> Fixes for Model Data Types creation and display

package-lock.json, src/app/model/access.ts, src/app/services/handlers/security-handler.service.ts, src/app/shared/profile-data-view/profile-data-view.component.ts
Change required to use the new `finalisedEditActions` and `finalisedReadActions` sent from the backend. This is required to get the DOI submission options to appear.
=> MC-9563 Update availableActions with corrected names

angular.json, src/app/security/open-id-connect-authorize/open-id-connect-authorize.component.ts, src/app/services/handlers/security-handler.service.ts, src/static-pages/open-id-connect-redirect.html
Required because some OpenID Connect providers do not allow URI fragments (hashes) in their redirect URLs, against the standards.
* Add new "asset" to Angular app which is a static HTML page. This immediately redirects to the original route, and is only provided for external sites to use.
* Fix issues with the `OpenIdConnectAuthorizeComponent`
Fixes #281
=> #281 Add static landing page/route for OpenID Connect redirect

package-lock.json, package.json, src/app/modals/edit-profile-modal/edit-profile-modal.component.html, src/app/modals/edit-profile-modal/edit-profile-modal.component.ts, src/app/shared/profile-details/profile-details.component.html, src/app/shared/profile-details/profile-details.component.ts
Fixes #284
* Uses correct property names and data types returned from profiles - names have been made more consistent
* Supports uneditable fields
* Validation endpoint now returns a collection of errors when a `422` is returned, so UI has been updated to reflect this
* Fixed required fields by looking at `minMultiplicity` field property
=> Update profiles to support changes on backend

Jenkinsfile, jest.config.js, package.json
* If the env variable BUILD_TAG exists then the cache dir should use that, otherwise defaults to "cache".
The full path is /tmp/jest_<BUILD_TAG> or /tmp/jest_cache.
fixes #278
=> gh-278 Add dynamic cacheDirectory for jest

.eslintignore, .npmrc, Jenkinsfile, README.md, license-check-and-add-config.json, package-lock.json, package.json
Updates to use the published mdm-resources
* no reliance on github
* updated readme
* updated jenkinsfile to use linked mdm-resources develop branch for ALL branches other than main
* updated jenkinsfile to use published mdm-resources for main branch
This means the mdm-ui will now have a reliance on mdm-resources develop branch having run with any required changes before the mdm-ui develop branch will complete.
See MauroDataMapper/mdm-resources#33
=> Updates to mdm-resources

src/app/admin/subscribed-catalogue/subscribed-catalogue.component.html, src/app/admin/subscribed-catalogue/subscribed-catalogue.component.ts, src/app/admin/subscribed-catalogues/subscribed-catalogues.component.html
Without an API key, the subscribed catalogue can only return publicly readable models.
With the API key, the subscribed catalogue can return non-public models.
Resolves #314
=> #314 Make API key field optional for subscribed catalogue setup

src/app/code-set/code-set/code-set.component.html, src/app/dataModel/data-model.component.html, src/app/folder/folder.component.html, src/app/referenceData/reference-data.component.html, src/app/terminology/terminology.component.html
Required for Cypress tests to understand low level details of current item displayed, such as ID and domain type.
=> MC-9642 Add data attributes to top-level catalogue item containers

src/app/model-selector-tree/model-selector-tree.component.spec.ts, src/app/model-selector-tree/model-selector-tree.component.ts
Clicking the advanced search link when not logged in was resulting in an incorrect request call to load tree endpoint.
=> GH-382 Fix to load tree with default filters

src/app/subscribed-catalogues/federated-data-model-main/federated-data-model-main.component.ts
After subscribing, the router would navigate back to the same page and pass the loaded model as a route parameter. Because no other navigation sites pass this parameter, it hung around for subsequent calls causing the page to not to load the correct selection from the model tree.
Fixes #412
=> #412 Fix refresh of federated models after subscribing to an external model

src/app/diagram/services/umlclass-diagram.service.ts
gh-401 Data Model Schema diagrams only showed one reference link between data classes when there were mutlitple links between classses. 
Solution: Updated the diagram to use unique reference ids.  
Original ids were created from the link source id and and link label, but label was always null. 
New ids are craeted from the link soruce id and the link name.
=> gh-401 Updated schema diagrams to have unique reference ids

src/app/subscribed-catalogues/federated-data-model-main/federated-data-model-main.component.html, src/app/subscribed-catalogues/federated-data-model-main/federated-data-model-main.component.ts, src/app/subscribed-catalogues/newer-versions/newer-versions.component.html, src/app/subscribed-catalogues/newer-versions/newer-versions.component.ts
If the API is not present in older instances, the UI will ignore.
Fixes #419
=> #419 Fix 40X HTTP issues when requesting newer versions of models in subscribed catalogues

src/app/shared/data-elements-list/data-elements-list.component.ts
gh-413 Removed hard-coded sort by idx for Data Elements, as it was overriding the sortBy parameter in the method.
=> gh-413 Fix to Data Elements sort

src/app/wizards/dataElement/data-element-step2/data-element-step2.component.ts
Closes #438 by reverting a change made in the previous commit.
The Data Class ID, rather than Data Model ID, was erroneously being used when listing Data Types on a Data Model.
=> gh-438 Use the dataModelId when listing Data Types on a Data Model

src/app/wizards/dataElement/data-element-step2/data-element-step2.component.ts
Closes #440 by reverting a previous change.
The Data Model ID was not being used when listing Data Elements.
=> gh-440 use modelId rather than model

src/app/folders-tree/folders-tree.component.ts, src/app/model-selector-tree/model-selector-tree.component.ts
* Folders returned for the tree root no longer auto-expand, so ensure that every container can be expanded on request
* Send modelCreatableOnly param for the tree view in the import screens
**Note:** this PR can be converted from draft once `MauroDataMapper/mdm-core` branch `feature/mc-9801` has been merged.
=> MC-9802 Update tree control with endpoint updates

src/app/utility/multiple-terms-selector/multiple-terms-selector.component.ts
Resolves #407 
The call to fetch the available terminologies was simply missing query parameters to return all (no pagination) and set correct sort order of results.
=> #407 Choose terminology for codeset now returns full ordered list

src/app/model/defaultProfileModel.ts, src/app/shared/default-profile/default-profile.component.html, src/app/shared/profile-data-view/profile-data-view.model.ts
By adding the term code to the default profile, selecting "Edit" allows the user to make changes to it.
Resolves #481
=> #481 Add term code to default profile to allow edits

src/app/utility/html-editor/html-editor.component.ts
Add both toolbar options to insert internal (catalogue items) and external links.
Resolves #465
=> #465 Add external link option to Jodit editor

src/app/utility/markdown/markdown-parser/custom-html-renderer.service.ts
Renderer was not setting correct href on anchor tags when an external URL was provided to another site, only internal links were considered.
Now updated to render both internal and external links:
Fixes #474
=> #474 Fix markdown renderer hyperlinks

src/app/modals/add-profile-modal/add-profile-modal.component.ts, src/app/modals/edit-profile-modal/edit-profile-modal.component.html, src/app/modals/edit-profile-modal/edit-profile-modal.component.ts, src/app/shared/profile-data-view/profile-data-view.component.ts, src/app/shared/profile-data-view/profile-data-view.model.ts
Add version number to profile view/edit dropdown and allow backend to filter versions of profiles displayed (resolves gh-493)
=> Show version numbers in view/edit profiles dropdown

src/app/app.component.ts, src/app/constants/ui.types.ts, src/app/services/utility/user-settings-handler.service.ts, src/app/userArea/settings/settings.component.html, src/app/userArea/settings/settings.component.ts, src/app/utility/content-editor/content-editor.component.html, src/app/utility/content-editor/content-editor.component.spec.ts, src/app/utility/content-editor/content-editor.component.ts, src/app/utility/html-editor/html-editor.component.html
Resolves #499 
* Add type definitions to UserSettingsHandlerService. Add missing properties that were used and refactor to not mix promises
* Update user preferences page
* Update content editor to respect user preferences. If no preference is set, or is "auto", revert back to original behaviour of guessing appropriate format
User has choice between forcing content to be Markdown or HTML. If they pick "Automatic" (or don't make a choice), behaviour reverts to original, where format is best-guessed from existing text values.
=> gh-499 Add user preference for content editing format

src/app/app-routing.module.ts, src/app/app.module.ts, src/app/catalogue-search/catalogue-search.module.ts, src/app/catalogue-search/catalogue-search/catalogue-search.component.html, src/app/catalogue-search/catalogue-search/catalogue-search.component.scss, src/app/catalogue-search/catalogue-search/catalogue-search.component.spec.ts, src/app/catalogue-search/catalogue-search/catalogue-search.component.ts, src/app/model/api-properties.ts, src/app/navbar/navbar.component.html, src/app/navbar/navbar.component.ts, src/app/services/features.service.ts, src/environments/environment.prod.ts, src/environments/environment.ts
Resolves #523 
**Note:** this is the precursor to other new Catalogue Search tasks, namely:
* #524 
* #525 
* #526 
* #527 
* #528 
* #529 
This PR must be approved and merged before these issues can start. Also, this PR is designed to only produce a rudimentary skeleton for initial work to start, the landing page currently implemented will just show nothing at the moment.
To be able to see the new (initial) Catalogue Search page, you need to either:
* Add the `feature.use_catalogue_search` API property to your own Mauro instance (preferred), or
* Set the `useCatalogueSearch` boolean flag in `environment.ts`
* New Angular module to contain future components created
* First landing component created, initially empty
* Add feature switch to control access to new Catalogue Search or continue …
=> gh-523 Initial setup for new Catalogue Search

src/app/app-routing.module.ts, src/app/catalogue-search/breadcrumb/breadcrumb.component.html, src/app/catalogue-search/breadcrumb/breadcrumb.component.scss, src/app/catalogue-search/breadcrumb/breadcrumb.component.spec.ts, src/app/catalogue-search/breadcrumb/breadcrumb.component.ts, src/app/catalogue-search/catalogue-item-search-result/catalogue-item-search-result.component.html, src/app/catalogue-search/catalogue-item-search-result/catalogue-item-search-result.component.scss, src/app/catalogue-search/catalogue-item-search-result/catalogue-item-search-result.component.spec.ts, src/app/catalogue-search/catalogue-item-search-result/catalogue-item-search-result.component.ts, src/app/catalogue-search/catalogue-search-listing/catalogue-search-listing.component.html, src/app/catalogue-search/catalogue-search-listing/catalogue-search-listing.component.scss, src/app/catalogue-search/catalogue-search-listing/catalogue-search-listing.component.spec.ts, src/app/catalogue-search/catalogue-search-listing/catalogue-search-listing.component.ts, src/app/catalogue-search/catalogue-search.module.ts, src/app/catalogue-search/catalogue-search.service.spec.ts, src/app/catalogue-search/catalogue-search.service.ts, src/app/catalogue-search/catalogue-search.types.ts, src/app/model-selector-tree/model-selector-tree.component.ts, src/app/utility/element-selector.component.ts, src/environments/environment.ts, src/style/components/_custom.scss
Resolves #525 
Resolves #526
* Route added to render the new page - `/search/listing`
* Currently only displays the search term field, list of results and various messages (e.g. no results, error, loading, etc)
* Search service currently only does a full catalogue search, will require further domain type parents later
* Basic rendering of search results, with links to navigate to each item
**Note**: currently to test this new page you must directly go to the URL `/search/listing?search=<term>`. Eventually the work done in #524 will redirect to this page cohesively.
Also, the page has not implemented pagination (#527), sorting (#528) or filtering (#529) yet.
=> gh-525 Updated search results page

src/app/catalogue-search/catalogue-search-listing/catalogue-search-listing.component.html, src/app/catalogue-search/catalogue-search-listing/catalogue-search-listing.component.ts, src/app/catalogue-search/catalogue-search.types.ts, src/app/catalogue-search/search-filters/search-filters.component.html, src/app/catalogue-search/search-filters/search-filters.component.scss, src/app/catalogue-search/search-filters/search-filters.component.spec.ts, src/app/catalogue-search/search-filters/search-filters.component.ts, src/style/components/_custom.scss
Improve catalogue item search filters as follows:
- Tidy up styles and alignments
- Add a 'Reset All' button
- Default labelOnly to true
- Change domainTypes filter to a mat-select
- Add a 'clear' button to the date fields
Known bug: if you click the 'Reset All' button twice in succession, on the second click the router seems to hang
Still to do: Add tree control to filter by a specific catalogue item
=> Feature/gh 529 ux - Improvements to catalogue item search filters

src/app/catalogue-search/catalogue-search-listing/catalogue-search-listing.component.spec.ts, src/app/catalogue-search/catalogue-search-listing/catalogue-search-listing.component.ts, src/app/catalogue-search/search-filters/search-filters.component.ts
Fixes #570 
Due to the way the UI Router works when it decides no transition between routes is required, the loading screen was accidentally kept on preventing the user from doing anything else. This PR resolves that issue.
=> gh-570 Fix search reset bug which sticks on loading screen

src/app/mauro/mauro-item-provider.service.spec.ts, src/app/mauro/mauro-item-provider.service.ts, src/app/mauro/mauro-item-update.service.spec.ts, src/app/mauro/mauro-item-update.service.ts, src/app/mauro/mauro-item.types.ts, src/app/mauro/profiles/default-profile-provider.service.spec.ts, src/app/mauro/profiles/default-profile-provider.service.ts
Interception service responsible for mapping catalogue item hardwired properties to a `Profile` object and back. This then allows the profile to be applied to other UI controls that require only a profile.
* Map original Mauro profile operations so that a in-memory profile object can be managed
* Create additional helper services to get/set any kind of Mauro item using only minimal identifier information. This circumvents the usual Mauro APIs which require you to know the domain you're working in upfront
* Full test suite provided
Resolves #591 
**Note:** the `DefaultProfileProviderService` isn't injected anywhere at the moment. Once approved, this is planned to be integrated into the bulk editor in issue #592
=> gh-951 Create DefaultProfileProviderService

src/app/catalogue-search/catalogue-item-search-result/catalogue-item-search-result.component.html
Using the more-description component to manage large descriptions. See ss for new page.
=> small change to better manage large descriptions

src/app/admin/subscribed-catalogue/subscribed-catalogue.component.html, src/app/admin/subscribed-catalogue/subscribed-catalogue.component.ts, src/app/admin/subscribed-catalogues/subscribed-catalogues.component.html, src/app/model/federated-data-model.ts, src/app/modules/resources/mdm-resources.service.ts, src/app/services/model-tree.service.ts, src/app/subscribed-catalogues/federated-data-model-detail/federated-data-model-detail.component.html, src/app/subscribed-catalogues/federated-data-model-detail/federated-data-model-detail.component.ts, src/app/subscribed-catalogues/federated-data-model-main/federated-data-model-main.component.html, src/app/subscribed-catalogues/federated-data-model-main/federated-data-model-main.component.ts, src/app/subscribed-catalogues/new-federated-subscription-modal/new-federated-subscription-modal.component.html, src/app/subscribed-catalogues/new-federated-subscription-modal/new-federated-subscription-modal.component.spec.ts, src/app/subscribed-catalogues/new-federated-subscription-modal/new-federated-subscription-modal.component.ts, src/app/subscribed-catalogues/newer-versions/newer-versions.component.html, src/app/subscribed-catalogues/subscribed-catalogue-detail/subscribed-catalogue-detail.component.html, src/app/subscribed-catalogues/subscribed-catalogue-detail/subscribed-catalogue-detail.component.spec.ts, src/app/subscribed-catalogues/subscribed-catalogues.service.ts
**Note:** this depends on MauroDataMapper/mdm-resources#71
* Update admin setup forms to use Angular reactive forms
* Add new connection type field to add/edit subscribed catalogue
* Display connection type of each subscribed catalogue in the list view
* Handle case where published model type is not known
* Display published data model dates
* Update Subscribe Data Model dialog to use Angular reactive forms
* Send additional properties during subscribed model creation - content link and/or importer
Admin screen of subscribed catalogues with subscribed catalogue types:
Inclusion of dates from published data models:
Updates to subscribe dialog:
=> MC-9891 Update subscribed catalogue UI due to breaking core changes

src/app/model/api-properties.ts, src/app/shared/models/models.component.html, src/app/shared/models/models.component.ts
gh-245 Created configuration to limit ability of non-admin users to create root folders or move exisiting folders to the root. 
Created configuration to limit ability of non-admin users to create classifiers
Configuration 
category:  security
key: security.restrict.root.folder
category: security
key: security.restrict.classifier.create
=> gh-245 Restrict ability to create folders and classifiers

src/app/folders-tree/folders-tree.component.ts
When an admin user selects the Show Deleted Models filter option, the data models that are marked as deleted should show in the browse tree with a strikethrough font.
=> gh-618 Show mark as deleted data models to admins

src/app/bulk-edit/bulk-edit-editor/bulk-edit-editor.component.ts, src/app/bulk-edit/bulk-edit-editor/cell-renderers/path-cell-renderer/path-cell-renderer.component.html, src/app/bulk-edit/bulk-edit-editor/cell-renderers/path-cell-renderer/path-cell-renderer.component.scss, src/app/bulk-edit/bulk-edit-editor/cell-renderers/path-cell-renderer/path-cell-renderer.component.spec.ts, src/app/bulk-edit/bulk-edit-editor/cell-renderers/path-cell-renderer/path-cell-renderer.component.ts, src/app/bulk-edit/bulk-edit-profile.service.ts, src/app/bulk-edit/bulk-edit.types.ts, src/app/mauro/mauro-item.types.ts, src/app/mauro/profiles/default-profile-provider.service.ts, src/app/mauro/profiles/mauro-profile-provider.service.ts, src/app/mauro/profiles/profile-provider-service.ts, src/app/shared/path-name/path-name.model.ts, src/app/shared/path-name/path-name.service.spec.ts, src/app/shared/path-name/path-name.service.ts
Model changes for https://github.com/MauroDataMapper/mdm-ui/compare/feature/gh-580-bulkedit-path
=> Resizable path column in bulkeditor

src/app/dataModel/data-model-detail.component.html, src/app/dataModel/data-model-detail.component.ts, src/app/export-models/export-models.component.html, src/app/export-models/export-models.component.scss, src/app/export-models/export-models.component.ts, src/app/import-models/import-models.component.html, src/app/import-models/import-models.component.ts, src/app/modals/export-model-dialog/export-model-dialog.component.html, src/app/modals/export-model-dialog/export-model-dialog.component.scss, src/app/modals/export-model-dialog/export-model-dialog.component.spec.ts, src/app/modals/export-model-dialog/export-model-dialog.component.ts, src/app/modals/modal.module.ts, src/app/model-selector-tree/model-selector-tree.component.ts, src/app/modules/catalogue/catalogue.module.ts, src/app/modules/resources/mdm-resources.models.ts, src/app/modules/resources/mdm-resources.service.ts, src/app/modules/shared/shared.module.ts, src/app/referenceData/reference-data-details/reference-data-details.component.html, src/app/referenceData/reference-data-details/reference-data-details.component.ts, src/app/services/element-types.service.ts, src/app/services/handlers/export-handler.service.ts, src/app/shared/new-version/new-version.component.html, src/app/shared/new-version/new-version.component.ts, src/app/terminology/terminology-details/terminology-details.component.html, src/app/terminology/terminology-details/terminology-details.component.ts, src/app/userArea/async-job-detail/async-job-detail.component.html, src/app/utility/element-link/element-link.component.ts, src/app/utility/extensions/mat-dialog.extensions.ts
* Update fork/branch/version of models to allow asynchronous creation
* Update versioned folders to support async fork/branch/version
* Updates to Import Models page
* Add async option to Export Models page
* Update model detail pages to support exports. Use a dialog to select export options now.
* Prevent export models from mixing domain types in model selection
* Use mdm-download-links component for Export Models page
* Update infrastructure code to get correct MDM resource easier
* Refactor other related code for type correctness
All async actions will display an info toast, if successful, stating the background job has started.
Branching/versioning/forking:
Export model (from model detail - new dialog):
Export models (multiple):
Import models - parameters pulled directly from importer …
=> MC-9841 Update UI to support certain actions that can run async in Mauro

src/app/modals/add-profile-modal/add-profile-modal.component.html, src/app/modals/add-profile-modal/add-profile-modal.component.ts, src/app/modals/edit-profile-modal/edit-profile-modal.component.html, src/app/modals/edit-profile-modal/edit-profile-modal.component.ts, src/app/modals/edit-profile-modal/edit-profile-modal.model.ts, src/app/shared/profile-data-view/profile-data-view.component.html, src/app/shared/profile-data-view/profile-data-view.component.ts, src/app/shared/profile-data-view/profile-data-view.model.ts
* Show edit profile button for profiles that are editable after finalisation
* Make individual profile fields readonly under conditions: if profile field is uneditable, or if item is finalised but profile field is editable after finalisation it overrides the readonly state
* Display info messages when item is finalised to make it clear to users
* Allow certain profiles to be added after finalisation. Only profiles with the editableAfterFinalisation flag can still be added
Item is finalised but can still edit parts of this profile:
Add further profiles to a finalised item, but only suitable profiles:
=> MC-9621 Allow UI to make updates to profiles editable after finalisation

src/app/app.module.ts, src/app/bulk-edit/bulk-edit.module.ts, src/app/catalogue-search/catalogue-search.module.ts, src/app/folders-tree/flat-node.ts, src/app/mauro/mauro-item-provider.service.ts, src/app/mauro/mauro-item.types.ts, src/app/merge-diff/merge-diff.module.ts, src/app/modals/modal.module.ts, src/app/modules/admin/admin.module.ts, src/app/modules/catalogue/catalogue.module.ts, src/app/modules/users/users.module.ts, src/app/services/handlers/favourite-handler.service.ts, src/app/shared/favourites/favourites.component.ts, src/app/shared/mauro-item-tree/mauro-item-tree.component.html, src/app/shared/mauro-item-tree/mauro-item-tree.component.scss, src/app/shared/mauro-item-tree/mauro-item-tree.component.spec.ts, src/app/shared/mauro-item-tree/mauro-item-tree.component.ts, src/app/shared/mauro-item-tree/mauro-item-tree.types.ts, src/app/shared/models/models.component.html, src/app/shared/models/models.component.ts, src/app/shared/shared.module.ts, src/app/testing/testing.module.ts, src/style/_main.scss
Resolves #588 
* Move `SharedModule` to correct sub-folder
* Create new `MauroItemTreeComponent` to create simplified tree view of catalogue items. Uses a custom Angular `DataSource` to handle fetching child items efficiently
* Simplify existing `FavouritesComponent` to fetch favourites items and display the tree view
* Match existing styles of tree views e.g. selection, show branch/versions, domain icons etc
* Navigate to any item selected in the tree, whether a favourite (root item) or expanded child
* Handle case where favourite catalogue items have been deleted by someone else
=> gh-588 Update Favourites view to be a tree view

src/app/utility/new-data-type-inline/new-data-type-inline.component.ts
After editing #652 I then realised that it would be better if the models were sorted.  This minor change fixes that.
=> Sort the models in the new inline data type component

src/app/folders-tree/folders-tree.component.ts, src/app/services/model-tree.service.ts, src/app/shared/models/models.component.html
Resolves #490 
Without superseded models...
With superseded models...
Option selection is cached to user's settings just like "Show Deleted Models"
=> gh-490 Add tree option to view superseded models

src/app/admin/emails/emails.component.html, src/app/admin/pending-users-table/pending-users-table.component.html, src/app/shared/data-classes-list/data-classes-list.component.html, src/app/shared/data-elements-list/data-elements-list.component.html, src/app/shared/element-child-data-classes-list/element-child-data-classes-list.component.html, src/app/shared/element-child-data-elements-list/element-child-data-elements-list.component.html, src/app/shared/element-link-list/element-link-list.component.html, src/app/shared/element-owned-data-type-list/element-owned-data-type-list.component.html, src/app/shared/element-owned-data-type-list/element-owned-data-type-list.component.ts, src/app/shared/reference-data-element/reference-data-element.component.html, src/app/shared/reference-data-type/reference-data-type.component.html, src/app/shared/reference-data-values/reference-data-values.component.html, src/app/shared/summary-metadata/summary-metadata-table/summary-metadata-table.component.html, src/app/subscribed-catalogues/newer-versions/newer-versions.component.html, src/app/userArea/api-keys/api-keys.component.html, src/app/wizards/dataElement/data-element-step2/data-element-step2.component.html
message changes when filters are enabled and no items are available
=> Updated messages dynamic mesage added if filter on

src/app/term/create-term-relationship-dialog/create-term-relationship-dialog.component.ts
Bug was caused to no check for duplicate codes in a term, which are forced to be unique. Added a check for this and display an error when a user attempts to create a new term with a duplicate code, so the term code can be amended in window. Tested creating new and using existing terms for relationships. Auto Tests all pass.
=> gh-516 - Duplicate check added

src/app/shared/data-elements-list/data-elements-list.component.html, src/app/shared/data-elements-list/data-elements-list.component.ts
gh-662 Show the disploy order column for data elements so the user can view how custom profile properties will appear on Data Model details screens.
=> gh-662 New Display Order column for data element grid view

src/app/services/handlers/security-handler.service.spec.ts, src/app/services/handlers/security-handler.service.ts
gh-370 Updated the UI to show the Allow User & Group access icon when an element as the available action of finalisedEditActions. This will show the icon for finalized data models.
https://github.com/MauroDataMapper/mdm-core/issues/370
=> gh-370 Allow User & Group access icon for finalized models

src/app/modals/edit-profile-modal/edit-profile-modal.component.html, src/app/modals/edit-profile-modal/edit-profile-modal.component.ts, src/app/model/api-properties.ts, src/app/shared/profile-data-view/profile-data-view.component.html, src/app/shared/profile-data-view/profile-data-view.component.ts
gh-675 Added configuration that can hide the edit after finalization alerts found on profile edit and details screens.
config key: ui.show_can_edit_property_alert
default value: true
category: UI
=> gh-675 Show / Hide edit after finalization alerts

src/app/app.component.html, src/app/shared/models/models.component.html, src/index.html, src/style/_default.scss, src/style/_main.scss
- When page contains additional space in content, footer will also attach to the bottom of the screen
- If the page height requires vertical scrolling, footer will always be at the end of the page
- Remove model tree forced height
Resolves #680
=> gh-680 Make footer stick to bottom of page

src/app/services/element-types.service.ts, src/app/shared/classified-elements-list/classified-elements-list.component.html, src/app/shared/classified-elements-list/classified-elements-list.component.ts, src/app/utility/element-link/element-link.component.ts
gh-371 Updated the classifier elements screen to show a filter text box for the Type column. Updated the element-link component with a new config property to show a domain type without the DataType prefix as users would use DataType as a filter value when filtering the results, and the elements' type value is not prefixed with DataType.
=> gh-371 Add filtering for classifier elements screen

src/app/constraints-rules/constraints-rules.component.html, src/app/constraints-rules/constraints-rules.component.ts, src/app/modals/add-rule-modal/add-rule-modal.component.html, src/app/modals/add-rule-modal/add-rule-modal.component.ts, src/app/modals/add-rule-representation-modal/add-rule-representation-modal.component.html, src/app/modals/add-rule-representation-modal/add-rule-representation-modal.component.scss, src/app/modals/add-rule-representation-modal/add-rule-representation-modal.component.ts, src/app/shared/more-description/more-description.component.html, src/app/shared/more-description/more-description.component.scss, src/app/shared/more-description/more-description.component.ts
*Note:* requires MauroDataMapper/mdm-resources#79 to be merged first.
Resolves #709
- Use type definitions for rules from mdm-resources
- Fix sort order of rule languages filter
- Code cleanup
- Improve Add Rule  and Add Rule Representation dialog - use reactive forms, add type definitions
- Add JSON support to rule representations
- Hide export option if rule has no representations
- Improve expand/collapse buttons for representations
- Move common action buttons out of context menu and into the table row
- List the number of representations in the rules table, then shows if there are any
=> gh-709 Improvements to the Rules and Representations UI

src/app/bulk-edit/bulk-edit-container/bulk-edit-container.component.html, src/app/bulk-edit/bulk-edit-editor-group/bulk-edit-editor-group.component.html, src/app/bulk-edit/bulk-edit-editor-group/bulk-edit-editor-group.component.ts, src/app/bulk-edit/bulk-edit-select/bulk-edit-select.component.html, src/app/bulk-edit/bulk-edit-select/bulk-edit-select.component.ts, src/app/shared/element-label/element-label.component.ts
Fixes #731 - renaming of output / events to fix future lint issues in Angular 14
=> Rename outputs to match future lint rules

src/app/admin/subscribed-catalogue/subscribed-catalogue.component.html, src/app/admin/subscribed-catalogue/subscribed-catalogue.component.ts, src/app/admin/subscribed-catalogues/subscribed-catalogues.component.html, src/app/model/federated-data-model.ts, src/app/services/model-tree.service.ts, src/app/subscribed-catalogues/newer-versions/newer-versions.component.html, src/app/subscribed-catalogues/subscribed-catalogue-detail/subscribed-catalogue-detail.component.spec.ts
- Display versions (or model version tags) for Published Models in the tree entry for a Subscribed Catalogue.
- In the Subscribed Catalogue admin settings page, add fields to choose Authentication Type and required authentication fields for each type (No Authentication, API Key or OAuth (Client Credentials)).
Depends on https://github.com/MauroDataMapper/mdm-resources/pull/84.
=> Subscribed Catalogue changes to support multiple Authentication Types

src/app/shared/summary-metadata/summary-metadata-chart/summary-metadata-chart.component.ts, src/app/shared/summary-metadata/summary-metadata-table/summary-metadata-table.component.html
Shorten the labels on the chart so that the rotation doesn't spoil the appearance.  Also tweak the table column widths and title styling.
Before:
After:
=> Slight improvements to Summary Metadata bar chart presentation

src/app/admin/subscribed-catalogue/subscribed-catalogue.component.ts
This should fix the issue currently appearing in Jenkins:
```
Error: src/app/admin/subscribed-catalogue/subscribed-catalogue.component.ts:37:27 - error TS2307: Cannot find module '../../../../../mdm-resources/src' or its corresponding type declarations.
37 import {MdmResponse} from '../../../../../mdm-resources/src';
```
=> Fix import stopping dist build on Jenkins

src/app/admin/api-property/api-property.component.ts, src/app/admin/subscribed-catalogue/subscribed-catalogue.component.html, src/app/admin/subscribed-catalogue/subscribed-catalogue.component.ts, src/app/app.component.spec.ts, src/app/bulk-edit/bulk-edit-select/bulk-edit-select.component.ts, src/app/catalogue-search/catalogue-search-advanced/catalogue-search-advanced-form.component.spec.ts, src/app/catalogue-search/catalogue-search-advanced/catalogue-search-advanced-form.component.ts, src/app/catalogue-search/catalogue-search-form/catalogue-search-form.component.ts, src/app/catalogue-search/catalogue-search/catalogue-search.component.spec.ts, src/app/modals/add-rule-modal/add-rule-modal.component.ts, src/app/modals/add-rule-representation-modal/add-rule-representation-modal.component.ts, src/app/modals/change-branch-name-modal/change-branch-name-modal.component.ts, src/app/modals/change-label-modal/change-label-modal.component.ts, src/app/modals/export-model-dialog/export-model-dialog.component.ts, src/app/modals/login-modal/login-modal.component.spec.ts, src/app/modals/login-modal/login-modal.component.ts, src/app/modals/new-folder-modal/new-folder-modal.component.ts, src/app/subscribed-catalogues/new-federated-subscription-modal/new-federated-subscription-modal.component.ts, src/app/subscribed-catalogues/subscribed-catalogue-detail/subscribed-catalogue-detail.component.spec.ts, src/app/terminology/term-list/create-term-dialog/create-term-dialog.component.ts, src/app/terminology/term-relationship-type-list/create-term-relationship-type-dialog/create-term-relationship-type-dialog.component.ts, src/app/terminology/term-relationship-type-list/term-relationship-type-list.component.ts, src/app/wizards/codeSet/code-set-main/code-set-main.component.ts, src/app/wizards/dataModel/data-model-step1/data-model-step1.component.ts, src/app/wizards/referenceDataModel/reference-data-model-main/reference-data-model-main.component.ts, src/app/wizards/referenceDataType/new-reference-data-type-form/new-reference-data-type-form.component.ts, src/app/wizards/terminology/terminology-main/terminology-main.component.ts
Resolves #742 
Note that some existing forms have _not_ been updated as they seem more complex, these are:
- `mdm-new-version`
- `mdm-openid-connect-provider`
- `mdm-create-term-relationship-dialog`
All other uses of `FormGroup` have been updated to be strongly typed.
=> gh-742 Code updates to support Angular 14 typed forms
