MauroDataMapper/mdm-ui

src/app/modals/login-modal/login-modal.component.html
Fixes #88 
Minor change to "Log in" form button to make sure e2e tests consistently pass.
=> #88 Fix "Log in" button text

src/app/model-merging/model-merging.component.ts, src/app/shared/attachment-list/attachment-list.component.html, src/app/shared/attachment-list/attachment-list.component.ts
Fixes #100 
Fixed the attachment list component to correctly send filter/sort/pagination parameters to the endpoint and updated the UI to not flicker/lose focus while filtering.
Also refactored/tidied the component:
* Changed function declaration syntax
* Removed obsolete code
* Added type definitions where known
* Security access now comes from the parent element
=> Attachment list component filter fixes

src/environments/environment.prod.ts, src/environments/environment.ts
* Subscribed catalogues
* Dynamic profiles
Subscribed catalogues may still be optionally turned off via environment variable
=> Enable feature toggles by default

src/app/services/model-tree.service.ts, src/app/shared/models/models.component.ts
Change approach to fetch local folder tree and subscribed catalogues for tree nodes. Instead of fetching both in parallel, perform one request at a time to reduce response errors.
Fixes #115 
**Note to reviewers**: I advise you test this branch on your local instances too and verify that you do not get the 404 when the model tree reloads. Test either scenarios described in #115 - there does not seem to be any consistency on when it occurs, perhaps dependent on network.
=> #115 Fix model tree reload after certain actions

src/app/shared/annotation-list/annotation-list.component.ts
Fixes #116
Fix the sort feature of the `mdm-annotation-list` component.
Also tidied up the code.
=> Ability to sort annotations

package-lock.json, src/app/home/home.component.html, src/app/home/home.component.ts, src/style/abstracts/_helpers.scss
Navigates to MDM documentation site
Fixes #134
=> #134 Add "Learn more" button to home page

src/app/errors/error.component.ts, src/app/services/youtrack.service.ts, src/app/versioned-folder/versioned-folder-detail/versioned-folder-detail.component.ts
Set the "Subsystem" field to be "Server"
=> #148 Update YouTrack service to set more issue details

src/app/access/share-with/share-with.component.html, src/app/classification/classification-details/classification-details.component.html, src/app/code-set/code-set-details/code-set-details.component.html, src/app/dataModel/data-model-detail.component.html, src/app/folder/folder-detail.component.html, src/app/referenceData/reference-data-details/reference-data-details.component.html, src/app/terminology/terminology-details/terminology-details.component.html, src/app/versioned-folder/versioned-folder-detail/versioned-folder-detail.component.html
Also add "Authenticated users only" icon/status
=> #152 Organise readable icons in each detail view

src/app/app-routing.module.ts, src/app/classification/classification.component.html, src/app/classification/classification.component.ts, src/app/code-set/code-set/code-set.component.html, src/app/code-set/code-set/code-set.component.ts, src/app/data-type/data-type.component.html, src/app/data-type/data-type.component.ts, src/app/dataClass/data-class/data-class.component.html, src/app/dataClass/data-class/data-class.component.ts, src/app/dataElement/data-element/data-element.component.html, src/app/dataElement/data-element/data-element.component.ts, src/app/dataModel/data-model.component.html, src/app/dataModel/data-model.component.ts, src/app/folder/folder.component.html, src/app/folder/folder.component.ts, src/app/model/ui.model.ts, src/app/referenceData/reference-data.component.html, src/app/referenceData/reference-data.component.ts, src/app/term/term/term.component.html, src/app/term/term/term.component.ts, src/app/terminology/terminology.component.html, src/app/terminology/terminology.component.ts, src/app/versioned-folder/versioned-folder/versioned-folder.component.html, src/app/versioned-folder/versioned-folder/versioned-folder.component.ts
Fixes #154 
Re-order tabs so that "Annotations" is less prominent, usually one of the last ones in each tab view.
Also completed some refactoring work:
* All views have consistent tab layouts and behaviour
* Refactored tab index/name state to reduce duplicate code
=> Feature/gh 154 Reorder tabs

src/app/profiles-dashboard/profiles-dashboard.component.html, src/app/profiles-dashboard/profiles-dashboard.component.ts
Fixed the metadata field used.  Changes to the back-end will also select the correct version number
=> Update Dynamic Profile Dashboard (#163)

src/app/folders-tree/folders-tree.component.ts
* Versioned Folder support added
* Restrictions set so that Versioned Folders cannot be moved into other Versioned Folders
@gammonpeter - the code file has been formatted so finding the actual changes looks difficult. All changes were made in the `drag...()` functions inside `folders-tree.component.ts`
=> MC-9515 Update model tree drag and drop

src/app/wizards/codeSet/code-set-main/code-set-main.component.html, src/app/wizards/codeSet/code-set-main/code-set-main.component.ts
=> #178 Update Code Set wizard to use reactive forms

src/app/diagram/services/models-merging-diagram.service.ts
=> #186 Update model merge graph to highlight current data model

package-lock.json, package.json, src/index.html, src/styles.scss
To avoid situations where the client browser have no access to the Bootstrap CDN (e.g. offline development, or intranet environment without internet access), which causes UI layout/styling issues.
=> Moved Bootstrap CSS reference from index.html into styles.scss

package-lock.json, src/app/model-merging/model-merging.component.ts
* Update mdm-resources to use correct endpoint
* Check if children exist in tree, otherwise don't need to remove non-conflicts
Fixes #200
=> #200 Fixes to model merge

package-lock.json, src/app/folders-tree/flat-node.ts, src/app/folders-tree/folders-tree.component.html
=> Feature/gh 181 Update icons for catalogue domain types

src/app/app-routing.module.ts, src/app/app.module.ts, src/app/doi-redirect/doi-redirect.component.html, src/app/doi-redirect/doi-redirect.component.scss, src/app/doi-redirect/doi-redirect.component.ts, src/app/modules/admin/admin.module.ts, src/app/services/utility/state-role-access.service.ts
New UI landing page at URL route `/#/doi/{doi}` to automatically resolve a catalogue item given a DOI and then redirect to that catalogue item.
=> Feature/mc 9564 DOI Resolution landing page

src/app/modals/security-modal/security-modal.component.ts
=> #245 Allow user groups to be added to finalised models

src/app/merge-diff/merge-comparsion/merge-comparsion.component.ts, src/app/merge-diff/services/string-conflict.service.ts
=> #261 Fix string diff comparison if either of the compare strings are null

src/app/services/utility/state-role-access.service.ts
=> #258 Add Versioned Folder route as allowed for anonymous users

src/app/shared/profile-data-view/profile-data-view.component.ts
Edit profile dialog was missing namespace and name of the profile.
Fixes #267
=> #267 Fix validation of DOI profile during submission

src/app/shared/profile-data-view/profile-data-view.component.ts
Use a parent model to determine access if the catalogueItem selected is a child element type, like a Term or Data Class.
Fixes #268
=> #268 Fix DOI submission option permissions

src/app/shared/profile-data-view/profile-data-view.component.ts
Changes to the backend meant that binding the request body for the POST request caused issues if sending a JSON string - UI has to send an actual JSON object instead for values submitted to be maintained.
Fixes #272
=> #272 Fix profile saving issue

package-lock.json, src/app/modals/edit-profile-modal/edit-profile-modal.component.ts, src/app/shared/profile-data-view/profile-data-view.component.ts
* Update mdm-resources to use correct property name
* Fetch status of DOI after successful submission to refresh
* Fix profile function calls to send objects
Fixes #274
=> #274 Fix getting status of DOI on catalogue item

src/app/shared/profile-data-view/profile-data-view.component.ts
Remove logged in check, now allows any user to view profiles assigned to catalogue items
Fixes #275
=> #275 Allow anonymous users to view profiles

src/app/shared/profile-data-view/profile-data-view.component.ts
=> #280 Fix refresh of DOI profile after submit

src/app/code-set/code-set-details/code-set-details.component.html, src/app/code-set/code-set-details/code-set-details.component.ts, src/app/dataModel/data-model-detail.component.html, src/app/dataModel/data-model-detail.component.ts, src/app/folder/folder-detail.component.html, src/app/folders-tree/folders-tree.component.ts, src/app/modules/shared/shared.module.ts, src/app/referenceData/reference-data-details/reference-data-details.component.html, src/app/referenceData/reference-data-details/reference-data-details.component.ts, src/app/services/broadcast.model.ts, src/app/services/broadcast.service.ts, src/app/services/handlers/favourite-handler.service.ts, src/app/shared/favorite-button/favorite-button.component.html, src/app/shared/favorite-button/favorite-button.component.scss, src/app/shared/favorite-button/favorite-button.component.spec.ts, src/app/shared/favorite-button/favorite-button.component.ts, src/app/shared/favourites/favourites.component.ts, src/app/term/term-details/term-details.component.ts, src/app/terminology/terminology-details/terminology-details.component.html, src/app/terminology/terminology-details/terminology-details.component.ts, src/app/versioned-folder/versioned-folder-detail/versioned-folder-detail.component.html
Resolves #249 
Updates to favourites support:
* Dedicated "favourite" button component added to all view where favourites can be saved (including some missing views)
* Updated broadcast of favourites. When added or removed, other components now respond correctly to these changes e.g. Favourites list refreshes
=> Fix interactivity with adding/removing favourites

src/app/shared/profile-data-view/profile-data-view.component.ts
=> Feature/gh 292 Fix refresh of views after DOI submission

src/app/modals/edit-profile-modal/edit-profile-modal.component.html, src/app/modals/edit-profile-modal/edit-profile-modal.component.ts
* Display "OK" message if no validation errors in profile
* Display count of validation errors found if more than zero
* Pre-validate form when dialog is opened to show current state
Resolves #291
=> #291 Clearer profile form validation

package-lock.json, src/app/shared/profile-data-view/profile-data-view.component.html, src/app/shared/profile-data-view/profile-data-view.component.ts
=> #298 Fix status updates of DOI to support retired status

src/app/doi-redirect/doi-redirect.component.ts
* Use correct state name for data types
* Add default `dataClassId` for Data Classes without a parent DC
Fixes #293
=> #293 Fix redirect of DOI catalogue items

src/app/modals/edit-profile-modal/edit-profile-modal.component.html, src/app/shared/profile-details/profile-details.component.html
=> #290 Hide profile field help icons when field description is missing

src/app/data-type/data-type-detail/data-type-detail.component.html, src/app/dataClass/data-class-details/data-class-details.component.html, src/app/dataElement/data-element-details/data-element-details.component.html, src/app/term/term-details/term-details.component.html
=> gh-229 Update detail view icons for consistency

src/app/services/content-search.handler.service.ts
Incorrect search endpoint used when searching within a chosen folder
Fixes #300
=> gh-300 Fix advanced search using folder as context

src/app/terminology/terminology.component.ts
Need to set the fetch() function to be property based so that the `mdm-select` child component can bind to it correctly
Resolves #308
=> gh-308 Fix term search

src/environments/environment.prod.ts
Can now use versioned folders and new merge-diff UI for merging
=> Change feature switch defaults for model families

src/app/classification/classification-details/classification-details.component.ts, src/app/services/broadcast.model.ts, src/app/services/broadcast.service.ts, src/app/shared/models/models.component.ts
=> #337 Update classification list when one is deleted

src/app/constraints-rules/constraints-rules.component.ts
=> #333 Emit new rule count when a rule is added to a catalogue item

src/app/search/advanced-search-bar/advanced-search-bar.component.ts, src/app/utility/element-classifications/element-classifications.component.ts
=> #430 Display all classifiers in selection list

src/app/utility/markdown/markdown-parser/link-creator.service.spec.ts, src/app/utility/markdown/markdown-parser/link-creator.service.ts
gh-442 Added processing for http element types when parsing text to html
=> gh-442 Return original url from HTML link parser for http element types

src/app/utility/markdown/markdown-parser/link-creator.service.spec.ts, src/app/utility/markdown/markdown-parser/link-creator.service.ts
gh-446 Update to link creator to return the mailto link for emails
=> gh-446 Update HTML parser for mailto links

Jenkinsfile, jest.config.js
Match changes made for the research portal,
allows additional reporting
=> Update jenkins build and jest config

src/app/bulk-edit/bulk-edit-select/bulk-edit-select.component.html, src/app/modals/add-profile-modal/add-profile-modal.component.html, src/app/modals/add-profile-modal/add-profile-modal.component.ts
Resolves #402 by listing the version number next to the profile display name
=> Include version number of profiles when selecting to add/edit

src/app/model/defaultProfileModel.ts, src/app/shared/default-profile/default-profile.component.html, src/app/shared/profile-data-view/profile-data-view.model.ts, src/app/terminology/term-list/create-term-dialog/create-term-dialog.component.html, src/app/terminology/term-list/create-term-dialog/create-term-dialog.component.scss, src/app/terminology/term-list/create-term-dialog/create-term-dialog.component.ts, src/app/terminology/term-list/term-list.component.ts, src/app/terminology/terminology.component.html, src/app/terminology/terminology.component.ts
* Adjust window size to be bigger
* Description field now use a HTML/Markdown editor
* Definition field is now optional
* Once created, you are redirected to the new term created
Resolves #476
=> #476 Updates to Create Term dialog

src/app/terminology/term-list/term-list.component.html, src/app/terminology/term-list/term-list.component.ts
Refactor to correctly use table data source and manage filters
Resolves #475
=> gh-475 Add filter controls to Terms list table

src/app/code-set/code-set/code-set.component.html, src/app/shared/code-set-terms-table/code-set-terms-table.component.ts
=> Set the access when configuring the code set table

package-lock.json, package.json, src/app/modules/catalogue/catalogue.module.ts
Resolves #550
Merging this issue is required in order for Renovate PRs to be built successfully.
=> gh-550 Remove ngx-text-diff package

src/app/app-routing.module.ts, src/app/catalogue-search/catalogue-search-listing/catalogue-search-listing.component.html, src/app/catalogue-search/catalogue-search-listing/catalogue-search-listing.component.spec.ts, src/app/catalogue-search/catalogue-search-listing/catalogue-search-listing.component.ts, src/app/catalogue-search/catalogue-search.service.ts, src/app/catalogue-search/catalogue-search.types.ts, src/app/shared/mdm-paginator/mdm-paginator.ts
Add paginator control to catalogue search listing page.
Closes #527
=> Feature/gh 527 - Pagination on search listing

src/app/catalogue-search/catalogue-search-listing/catalogue-search-listing.component.html, src/app/catalogue-search/catalogue-search-listing/catalogue-search-listing.component.ts, src/app/modules/shared/shared.module.ts, src/app/shared/sort-by/sort-by.component.html, src/app/shared/sort-by/sort-by.component.scss, src/app/shared/sort-by/sort-by.component.spec.ts, src/app/shared/sort-by/sort-by.component.ts
Add a SortBy component, and add this to the catalogue search listing page.
Closes #528
=> Feature/gh 528 - Sort search results

src/app/catalogue-search/catalogue-search/catalogue-search.component.spec.ts, src/app/catalogue-search/catalogue-search/catalogue-search.component.ts
Changes to match the expected context parameters
Updated tests to include new params
=> Fixed tests and context bug

src/app/import-models/import-models.component.html
Update the styling of the import model form to match the profile editor:
Before:
After:
More work to be done, but I can put this into another ticket
=> Update the styling of the import model form

src/app/model/api-properties.ts, src/app/shared/profile-data-view/profile-data-view.component.ts
gh-597
New configuration to simplify entry of the default profile view to include all items in the hierarchy.
=> gh-597 Added configurable simplified entry of default profile view

src/app/admin/app-container/app-container.component.html, src/app/modules/resources/mdm-resources.service.ts, src/app/modules/users-routes/users-routes.module.ts, src/app/modules/users/users.module.ts, src/app/navbar/navbar.component.html, src/app/services/grid.service.ts, src/app/userArea/async-job-detail/async-job-detail.component.html, src/app/userArea/async-job-detail/async-job-detail.component.scss, src/app/userArea/async-job-detail/async-job-detail.component.spec.ts, src/app/userArea/async-job-detail/async-job-detail.component.ts, src/app/userArea/async-job-list/async-job-list.component.html, src/app/userArea/async-job-list/async-job-list.component.scss, src/app/userArea/async-job-list/async-job-list.component.spec.ts, src/app/userArea/async-job-list/async-job-list.component.ts, src/app/users/users-app-container/users-app-container.component.html
* New page added to user profile area
* Supports filtering, sorting and pagination
* View and cancel async jobs
List async jobs available:
Details on a single job:
=> MC-9840 Display async jobs for a user

src/app/catalogue-search/catalogue-search-advanced/catalogue-search-advanced-form.component.html, src/app/modals/catalogue-item-select-modal/catalogue-item-select-modal.component.html
Commit https://github.com/MauroDataMapper/mdm-ui/commit/38993273408333cb267f52d9134ca68e8bcc34c9 fixed the search service for terminologies to use the endpoint POST /api/terminologies/{id}/terms/search 
This PR allows Terminologies to be selected for search.
Partial fix for #600
=> gh-600 terminology search

src/app/terminology/term-list/term-list.component.html
=> gh-627 typo fix

src/app/admin/app-container/app-container.component.html, src/app/modules/catalogue/catalogue.module.ts, src/app/modules/resources/mdm-resources.service.ts, src/app/modules/shared/shared.module.ts, src/app/modules/users-routes/users-routes.module.ts, src/app/modules/users/users.module.ts, src/app/navbar/navbar.component.html, src/app/services/handlers/export-handler.service.ts, src/app/userArea/domain-exports-detail/domain-exports-detail.component.html, src/app/userArea/domain-exports-detail/domain-exports-detail.component.scss, src/app/userArea/domain-exports-detail/domain-exports-detail.component.spec.ts, src/app/userArea/domain-exports-detail/domain-exports-detail.component.ts, src/app/userArea/domain-exports-list/domain-exports-list.component.html, src/app/userArea/domain-exports-list/domain-exports-list.component.scss, src/app/userArea/domain-exports-list/domain-exports-list.component.spec.ts, src/app/userArea/domain-exports-list/domain-exports-list.component.ts, src/app/users/users-app-container/users-app-container.component.html
* New page added to user profile area
* Supports filtering, sorting and pagination
* View, download and delete exports
List available exported models:
Details of an export:
=> MC-9889 Display domain models exported asynchronously

src/app/terminology/term-list/term-list.component.html, src/app/terminology/term-list/term-list.component.ts
=> Display description column on term list

src/app/shared/element-label/element-label.component.html, src/app/shared/element-label/element-label.component.scss, src/app/shared/element-label/element-label.component.ts, src/app/shared/mauro-item-tree/mauro-item-tree.component.html, src/app/shared/shared.module.ts, src/app/utility/element-selector.component.html, src/app/utility/element-selector.component.ts, src/app/utility/multiple-terms-selector/multiple-terms-selector.component.html, src/app/utility/new-data-type-inline/new-data-type-inline.component.html, src/app/utility/new-data-type-inline/new-data-type-inline.component.ts
=> gh-492 Display version and branch name of terminology when selecting for Code Sets

src/app/shared/classified-elements-list/classified-elements-list.component.html
gh-664 Fix for sort issue with Types column on Classifier Details > Elements tab
=> gh-664 Add sort by catalogue item type

src/app/modals/edit-profile-modal/edit-profile-modal.component.html, src/app/modals/edit-profile-modal/edit-profile-modal.component.ts
* Use correct fieldTotal property for counting validation errors
* Don't validate the empty profile immediately on open, only when clicking the validate button
=> MC-9719 Fix profile validation issues

src/app/app-routing.module.ts, src/app/folders-tree/folders-tree.component.html, src/app/folders-tree/folders-tree.component.ts, src/app/modules/catalogue/catalogue.module.ts, src/app/services/handlers/state-handler.service.ts, src/app/wizards/codeSet/code-set-main/code-set-main.component.ts, src/app/wizards/dataModel/data-model-main/data-model-main.component.ts, src/app/wizards/referenceDataModel/reference-data-model-main/reference-data-model-main.component.html, src/app/wizards/referenceDataModel/reference-data-model-main/reference-data-model-main.component.scss, src/app/wizards/referenceDataModel/reference-data-model-main/reference-data-model-main.component.spec.ts, src/app/wizards/referenceDataModel/reference-data-model-main/reference-data-model-main.component.ts
Resolves #641 
**Note:** depends on MauroDataMapper/mdm-resources#74
* Update existing model wizards with latest shared endpoints
* Add option to create Reference Data Model
* Create wizard to create Reference Data Model
* Add tests for RDM wizard
=> gh-641 Add new Reference Data Model wizard

src/app/utility/loading-indicator/loading-indicator.component.ts
Ensure the LoadingIndicatorComponent updates bound properties correctly
=> Fix "ExpressionChangedAfterItHasBeenCheckedError"

src/app/app-routing.module.ts, src/app/dataModel/data-model.component.ts
gh-363 Provide a path in the UI to view the latest finalised datamodel
eg. http://localhost:4200/#/catalogue/dataModel/dm:DM_LABEL?finalised=true
=> gh-363 parameter to get latest finalised data model

src/app/modals/change-label-modal/change-label-modal.component.ts
Useful for users to start from something when making changes
Resolves #710
=> gh-710 Prepopulate Change Label dialog with original label

src/app/catalogue-search/catalogue-item-search-result/catalogue-item-search-result.component.scss, src/app/catalogue-search/search-filters/search-filters.component.scss, src/app/navbar/navbar.component.scss, src/app/shared/alert/alert.component.scss, src/app/shared/footer/footer.component.scss, src/app/shared/models/models.component.scss, src/style/themes/default.scss, src/style/themes/nhs-digital.scss, src/styles.scss
Fixes #724.  For merging before upgrade to angular 14
=> Update scss imports to not use '~'

src/app/admin/app-container/app-container.component.ts, src/app/app.component.ts, src/app/bulk-edit/bulk-edit-select/bulk-edit-select.component.ts, src/app/folders-tree/folders-tree.component.ts, src/app/home/home.component.ts, src/app/modals/modal.service.ts, src/app/navbar/navbar.component.ts, src/app/services/features.service.ts, src/app/services/model-tree.service.ts, src/app/shared/favorite-button/favorite-button.component.ts, src/app/shared/models/models.component.ts, src/app/wizards/dataModel/data-model-step1/data-model-step1.component.ts
Fixes #729 and helps simplify the upgrade to angular 14.
=> Properly type, and make consistent, all `unsubscribe$` `Subject` definitions

src/app/model/stepModel.ts, src/app/shared/sort-by/sort-by.component.ts, src/app/utility/extensions/mat-dialog.extensions.ts
Fixes #733 and simplifies the upgrade to angular 14
=> Update Angular Material import locations

src/app/admin/subscribed-catalogue/subscribed-catalogue.component.ts, src/app/shared/footer/footer.component.html, src/app/shared/footer/footer.component.scss, src/app/shared/footer/footer.component.ts, src/app/subscribed-catalogues/subscribed-catalogue-detail/subscribed-catalogue-detail.component.spec.ts
- Adjust footer links alignment
- Add copyright and "Powered by MDM" text/logo to right side
Resolves #681
=> gh-680 Restyle footer to always show MDM logo

src/app/bulk-edit/bulk-edit-container/bulk-edit-container.component.ts
Manually confirm with user they want to cancel and go back a page if they confirm.
Fixes #739
=> gh-739 Fix Bulk Editor cancel action

src/app/shared/footer/footer.component.html
This fixes the pathing issue that's stopping the image appearing in the footer on our hosted instances
=> Fix footer image path
